<script>
    const faqs = [
        {
            question: "What is an AI image detector?",
            answer: "An AI image detector analyzes digital images to determine whether they were created by a human or generated by artificial intelligence using deep learning models.",
        },
        {
            question: "What image formats are supported?",
            answer: "Currently, we support JPEG, PNG, and WebP formats with a maximum file size of 10 MB.",
        },
        {
            question: "How accurate is the detection?",
            answer: "While our model is highly trained, no AI detection tool is 100% accurate. We provide a probability score based on the analysis.",
        },
        {
            question: "Is my uploaded image stored?",
            answer: "The uploaded image will be stored as a base64-encoded string for the upload history in a local database. Additionally, the hash of the image will be cached for 30 minutes in the backend to speed up subsequent requests.",
        },
    ];
</script>

<section class="w-full bg-gray-50 py-20">
    <div class="max-w-6xl mx-auto px-4">
        <h2 class="text-3xl font-semibold text-center text-gray-800 mb-12">
            Frequently Asked Questions
        </h2>

        <div class="space-y-4">
            {#each faqs as faq}
                <div
                    class="collapse collapse-arrow bg-base-100 border border-base-300"
                >
                    <input type="checkbox" class="peer" />
                    <div
                        class="collapse-title font-semibold peer-checked:text-primary"
                    >
                        {faq.question}
                    </div>
                    <div class="collapse-content text-sm text-gray-600">
                        <p>{faq.answer}</p>
                    </div>
                </div>
            {/each}
        </div>
    </div>
</section>
